FairyRingNode:
  ip: "0.0.0.0"
  port: 26657
  protocol: "tcp"
  grpcport: 9090
  accountprefix: fairy
  chainid: fairytest-3

DestinationNode:
  ip: "0.0.0.0"
  port: 26659
  protocol: "tcp"
  grpcport: 9092
  accountprefix: fairy
  chainid: fairytest-3

derivepath: m/44'/118'/0'/0/0
Mnemonic: "cruise scene law sea push expose scorpion wire trick repair wave quote task dose inner denial alpha favorite certain blouse motion flash split lunch"